# Usar la imagen base de Nginx
FROM nginx:latest

# Copiar el archivo HTML a la ubicación predeterminada de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 8082
EXPOSE 8082

# Cambiar el puerto en la configuración de Nginx
RUN sed -i 's/listen 80;/listen 8082;/g' /etc/nginx/conf.d/default.conf
