name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "jeronimovelasquez"  
        password: "dckr_pat_RLjm68rZ2-OfGX2mNC5hIA4uXMg" 

    # Build the Docker image
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag jeronimovelasquez/my-image-name:latest  # Usa tu nombre de usuario

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push jeronimovelasquez/my-image-name:latest  # Usa tu nombre de usuario
