name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out the repository
      uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}   # Usa el secreto DOCKER_USERNAME de GitHub
        password: ${{ secrets.DOCKER_PASSWORD }}   # Usa el secreto DOCKER_PASSWORD de GitHub

    # Build the Docker image
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
